Repository python-babel/babel, pull requests merged in 2022-11, with the labels that each got.

#915 Use `ast` instead of `eval` for string extraction
  babel/messages/extract.py
  tests/messages/test_extract.py
Labels: bug, enhancement, area/messages

#916 Quiesce pytest warnings
  babel/numbers.py
  conftest.py
  tests/test_core.py
  tox.ini
Labels: bug, enhancement, size/S

#921 feat: Adds `Format.compact_decimal` utility
  babel/support.py
  tests/test_support.py
Labels: enhancement, area/numbers

#925 Remove vestigial Python 2 `long` check
  babel/numbers.py
Labels: enhancement

#930 Cast number to Decimal in _get_compact_format
  babel/numbers.py
Labels: bug, area/numbers

#927 Replace %/.format/concatenation with f-strings where feasible
  babel/core.py
  babel/dates.py
  babel/lists.py
  babel/localedata.py
  babel/localtime/_win32.py
  babel/messages/catalog.py
  babel/messages/checkers.py
  babel/messages/extract.py
  babel/messages/frontend.py
  babel/messages/pofile.py
  babel/numbers.py
  babel/plural.py
  babel/support.py
  babel/units.py
  babel/util.py
  scripts/generate_authors.py
  scripts/import_cldr.py
  setup.py
  tests/messages/test_catalog.py
  tests/messages/test_frontend.py
  tests/messages/test_pofile.py
  tests/test_core.py
  tests/test_plural.py
  tests/test_support.py
Labels: enhancement
