Repository python-babel/babel, pull requests merged in 2023-01, with the labels that each got.

#932 Fix compact singular formats and patterns with no numbers
  babel/numbers.py
  tests/test_numbers.py
Labels: area/numbers

#945 Unify datetime imports
  babel/dates.py
  babel/localtime/__init__.py
  babel/localtime/_unix.py
  babel/localtime/_win32.py
  babel/messages/catalog.py
  babel/messages/frontend.py
  babel/numbers.py
  babel/support.py
  babel/util.py
Labels: enhancement

#951 Upgrade to CLDR 42
  babel/core.py
  babel/dates.py
  babel/numbers.py
  babel/support.py
  scripts/download_import_cldr.py
  scripts/import_cldr.py
  tests/test_core.py
  tests/test_date_intervals.py
  tests/test_dates.py
  tests/test_numbers.py
  tests/test_support.py
Labels: area/CLDR

#953 Update test dependencies (tox v4)
  .github/workflows/test.yml
  tox.ini
Labels: enhancement

#952 Clean up babel.localtime
  babel/localtime/__init__.py
  babel/localtime/_fallback.py
  babel/util.py
Labels: enhancement

#957 Use standard library UTC
  babel/dates.py
Labels: area/dates

#947 Keep @modifiers when parsing locales
  babel/core.py
  tests/test_core.py
Labels: feature
